// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef PROTOBUF_INCLUDED_msg_2eproto
#define PROTOBUF_INCLUDED_msg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_msg_2eproto();
namespace bovo_message {
class BovoMessage;
class BovoMessageDefaultTypeInternal;
extern BovoMessageDefaultTypeInternal _BovoMessage_default_instance_;
}  // namespace bovo_message
namespace google {
namespace protobuf {
template<> ::bovo_message::BovoMessage* Arena::CreateMaybeMessage<::bovo_message::BovoMessage>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace bovo_message {

enum BovoMessage_CmdType {
  BovoMessage_CmdType_NONE = 0,
  BovoMessage_CmdType_JOIN = 1,
  BovoMessage_CmdType_STYLE = 2,
  BovoMessage_CmdType_PUT = 3,
  BovoMessage_CmdType_QUIT = 4,
  BovoMessage_CmdType_TOKEN = 5
};
bool BovoMessage_CmdType_IsValid(int value);
const BovoMessage_CmdType BovoMessage_CmdType_CmdType_MIN = BovoMessage_CmdType_NONE;
const BovoMessage_CmdType BovoMessage_CmdType_CmdType_MAX = BovoMessage_CmdType_TOKEN;
const int BovoMessage_CmdType_CmdType_ARRAYSIZE = BovoMessage_CmdType_CmdType_MAX + 1;

const ::google::protobuf::EnumDescriptor* BovoMessage_CmdType_descriptor();
inline const ::std::string& BovoMessage_CmdType_Name(BovoMessage_CmdType value) {
  return ::google::protobuf::internal::NameOfEnum(
    BovoMessage_CmdType_descriptor(), value);
}
inline bool BovoMessage_CmdType_Parse(
    const ::std::string& name, BovoMessage_CmdType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BovoMessage_CmdType>(
    BovoMessage_CmdType_descriptor(), name, value);
}
enum BovoMessage_StatusType {
  BovoMessage_StatusType_OKAY = 0,
  BovoMessage_StatusType_ERROR = 1,
  BovoMessage_StatusType_WON = 2,
  BovoMessage_StatusType_LOST = 3
};
bool BovoMessage_StatusType_IsValid(int value);
const BovoMessage_StatusType BovoMessage_StatusType_StatusType_MIN = BovoMessage_StatusType_OKAY;
const BovoMessage_StatusType BovoMessage_StatusType_StatusType_MAX = BovoMessage_StatusType_LOST;
const int BovoMessage_StatusType_StatusType_ARRAYSIZE = BovoMessage_StatusType_StatusType_MAX + 1;

const ::google::protobuf::EnumDescriptor* BovoMessage_StatusType_descriptor();
inline const ::std::string& BovoMessage_StatusType_Name(BovoMessage_StatusType value) {
  return ::google::protobuf::internal::NameOfEnum(
    BovoMessage_StatusType_descriptor(), value);
}
inline bool BovoMessage_StatusType_Parse(
    const ::std::string& name, BovoMessage_StatusType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<BovoMessage_StatusType>(
    BovoMessage_StatusType_descriptor(), name, value);
}
// ===================================================================

class BovoMessage final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:bovo_message.BovoMessage) */ {
 public:
  BovoMessage();
  virtual ~BovoMessage();

  BovoMessage(const BovoMessage& from);

  inline BovoMessage& operator=(const BovoMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BovoMessage(BovoMessage&& from) noexcept
    : BovoMessage() {
    *this = ::std::move(from);
  }

  inline BovoMessage& operator=(BovoMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const BovoMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BovoMessage* internal_default_instance() {
    return reinterpret_cast<const BovoMessage*>(
               &_BovoMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(BovoMessage* other);
  friend void swap(BovoMessage& a, BovoMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BovoMessage* New() const final {
    return CreateMaybeMessage<BovoMessage>(nullptr);
  }

  BovoMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<BovoMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const BovoMessage& from);
  void MergeFrom(const BovoMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BovoMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef BovoMessage_CmdType CmdType;
  static const CmdType NONE =
    BovoMessage_CmdType_NONE;
  static const CmdType JOIN =
    BovoMessage_CmdType_JOIN;
  static const CmdType STYLE =
    BovoMessage_CmdType_STYLE;
  static const CmdType PUT =
    BovoMessage_CmdType_PUT;
  static const CmdType QUIT =
    BovoMessage_CmdType_QUIT;
  static const CmdType TOKEN =
    BovoMessage_CmdType_TOKEN;
  static inline bool CmdType_IsValid(int value) {
    return BovoMessage_CmdType_IsValid(value);
  }
  static const CmdType CmdType_MIN =
    BovoMessage_CmdType_CmdType_MIN;
  static const CmdType CmdType_MAX =
    BovoMessage_CmdType_CmdType_MAX;
  static const int CmdType_ARRAYSIZE =
    BovoMessage_CmdType_CmdType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  CmdType_descriptor() {
    return BovoMessage_CmdType_descriptor();
  }
  static inline const ::std::string& CmdType_Name(CmdType value) {
    return BovoMessage_CmdType_Name(value);
  }
  static inline bool CmdType_Parse(const ::std::string& name,
      CmdType* value) {
    return BovoMessage_CmdType_Parse(name, value);
  }

  typedef BovoMessage_StatusType StatusType;
  static const StatusType OKAY =
    BovoMessage_StatusType_OKAY;
  static const StatusType ERROR =
    BovoMessage_StatusType_ERROR;
  static const StatusType WON =
    BovoMessage_StatusType_WON;
  static const StatusType LOST =
    BovoMessage_StatusType_LOST;
  static inline bool StatusType_IsValid(int value) {
    return BovoMessage_StatusType_IsValid(value);
  }
  static const StatusType StatusType_MIN =
    BovoMessage_StatusType_StatusType_MIN;
  static const StatusType StatusType_MAX =
    BovoMessage_StatusType_StatusType_MAX;
  static const int StatusType_ARRAYSIZE =
    BovoMessage_StatusType_StatusType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  StatusType_descriptor() {
    return BovoMessage_StatusType_descriptor();
  }
  static inline const ::std::string& StatusType_Name(StatusType value) {
    return BovoMessage_StatusType_Name(value);
  }
  static inline bool StatusType_Parse(const ::std::string& name,
      StatusType* value) {
    return BovoMessage_StatusType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional bytes name = 4;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 4;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const void* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional bytes address = 5;
  bool has_address() const;
  void clear_address();
  static const int kAddressFieldNumber = 5;
  const ::std::string& address() const;
  void set_address(const ::std::string& value);
  #if LANG_CXX11
  void set_address(::std::string&& value);
  #endif
  void set_address(const char* value);
  void set_address(const void* value, size_t size);
  ::std::string* mutable_address();
  ::std::string* release_address();
  void set_allocated_address(::std::string* address);

  // optional uint32 magic = 1;
  bool has_magic() const;
  void clear_magic();
  static const int kMagicFieldNumber = 1;
  ::google::protobuf::uint32 magic() const;
  void set_magic(::google::protobuf::uint32 value);

  // required .bovo_message.BovoMessage.CmdType cmd = 2;
  bool has_cmd() const;
  void clear_cmd();
  static const int kCmdFieldNumber = 2;
  ::bovo_message::BovoMessage_CmdType cmd() const;
  void set_cmd(::bovo_message::BovoMessage_CmdType value);

  // optional .bovo_message.BovoMessage.StatusType status = 3;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 3;
  ::bovo_message::BovoMessage_StatusType status() const;
  void set_status(::bovo_message::BovoMessage_StatusType value);

  // optional uint32 markstyle = 6;
  bool has_markstyle() const;
  void clear_markstyle();
  static const int kMarkstyleFieldNumber = 6;
  ::google::protobuf::uint32 markstyle() const;
  void set_markstyle(::google::protobuf::uint32 value);

  // optional uint32 x = 7;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 7;
  ::google::protobuf::uint32 x() const;
  void set_x(::google::protobuf::uint32 value);

  // optional uint32 y = 8;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 8;
  ::google::protobuf::uint32 y() const;
  void set_y(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:bovo_message.BovoMessage)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr address_;
  ::google::protobuf::uint32 magic_;
  int cmd_;
  int status_;
  ::google::protobuf::uint32 markstyle_;
  ::google::protobuf::uint32 x_;
  ::google::protobuf::uint32 y_;
  friend struct ::TableStruct_msg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BovoMessage

// optional uint32 magic = 1;
inline bool BovoMessage::has_magic() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BovoMessage::clear_magic() {
  magic_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::google::protobuf::uint32 BovoMessage::magic() const {
  // @@protoc_insertion_point(field_get:bovo_message.BovoMessage.magic)
  return magic_;
}
inline void BovoMessage::set_magic(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  magic_ = value;
  // @@protoc_insertion_point(field_set:bovo_message.BovoMessage.magic)
}

// required .bovo_message.BovoMessage.CmdType cmd = 2;
inline bool BovoMessage::has_cmd() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BovoMessage::clear_cmd() {
  cmd_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::bovo_message::BovoMessage_CmdType BovoMessage::cmd() const {
  // @@protoc_insertion_point(field_get:bovo_message.BovoMessage.cmd)
  return static_cast< ::bovo_message::BovoMessage_CmdType >(cmd_);
}
inline void BovoMessage::set_cmd(::bovo_message::BovoMessage_CmdType value) {
  assert(::bovo_message::BovoMessage_CmdType_IsValid(value));
  _has_bits_[0] |= 0x00000008u;
  cmd_ = value;
  // @@protoc_insertion_point(field_set:bovo_message.BovoMessage.cmd)
}

// optional .bovo_message.BovoMessage.StatusType status = 3;
inline bool BovoMessage::has_status() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void BovoMessage::clear_status() {
  status_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::bovo_message::BovoMessage_StatusType BovoMessage::status() const {
  // @@protoc_insertion_point(field_get:bovo_message.BovoMessage.status)
  return static_cast< ::bovo_message::BovoMessage_StatusType >(status_);
}
inline void BovoMessage::set_status(::bovo_message::BovoMessage_StatusType value) {
  assert(::bovo_message::BovoMessage_StatusType_IsValid(value));
  _has_bits_[0] |= 0x00000010u;
  status_ = value;
  // @@protoc_insertion_point(field_set:bovo_message.BovoMessage.status)
}

// optional bytes name = 4;
inline bool BovoMessage::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BovoMessage::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& BovoMessage::name() const {
  // @@protoc_insertion_point(field_get:bovo_message.BovoMessage.name)
  return name_.GetNoArena();
}
inline void BovoMessage::set_name(const ::std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bovo_message.BovoMessage.name)
}
#if LANG_CXX11
inline void BovoMessage::set_name(::std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bovo_message.BovoMessage.name)
}
#endif
inline void BovoMessage::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bovo_message.BovoMessage.name)
}
inline void BovoMessage::set_name(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bovo_message.BovoMessage.name)
}
inline ::std::string* BovoMessage::mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_mutable:bovo_message.BovoMessage.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BovoMessage::release_name() {
  // @@protoc_insertion_point(field_release:bovo_message.BovoMessage.name)
  if (!has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BovoMessage::set_allocated_name(::std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:bovo_message.BovoMessage.name)
}

// optional bytes address = 5;
inline bool BovoMessage::has_address() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BovoMessage::clear_address() {
  address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& BovoMessage::address() const {
  // @@protoc_insertion_point(field_get:bovo_message.BovoMessage.address)
  return address_.GetNoArena();
}
inline void BovoMessage::set_address(const ::std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:bovo_message.BovoMessage.address)
}
#if LANG_CXX11
inline void BovoMessage::set_address(::std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  address_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:bovo_message.BovoMessage.address)
}
#endif
inline void BovoMessage::set_address(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:bovo_message.BovoMessage.address)
}
inline void BovoMessage::set_address(const void* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:bovo_message.BovoMessage.address)
}
inline ::std::string* BovoMessage::mutable_address() {
  _has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_mutable:bovo_message.BovoMessage.address)
  return address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* BovoMessage::release_address() {
  // @@protoc_insertion_point(field_release:bovo_message.BovoMessage.address)
  if (!has_address()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return address_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void BovoMessage::set_allocated_address(::std::string* address) {
  if (address != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), address);
  // @@protoc_insertion_point(field_set_allocated:bovo_message.BovoMessage.address)
}

// optional uint32 markstyle = 6;
inline bool BovoMessage::has_markstyle() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void BovoMessage::clear_markstyle() {
  markstyle_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::google::protobuf::uint32 BovoMessage::markstyle() const {
  // @@protoc_insertion_point(field_get:bovo_message.BovoMessage.markstyle)
  return markstyle_;
}
inline void BovoMessage::set_markstyle(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000020u;
  markstyle_ = value;
  // @@protoc_insertion_point(field_set:bovo_message.BovoMessage.markstyle)
}

// optional uint32 x = 7;
inline bool BovoMessage::has_x() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void BovoMessage::clear_x() {
  x_ = 0u;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::google::protobuf::uint32 BovoMessage::x() const {
  // @@protoc_insertion_point(field_get:bovo_message.BovoMessage.x)
  return x_;
}
inline void BovoMessage::set_x(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000040u;
  x_ = value;
  // @@protoc_insertion_point(field_set:bovo_message.BovoMessage.x)
}

// optional uint32 y = 8;
inline bool BovoMessage::has_y() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void BovoMessage::clear_y() {
  y_ = 0u;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::google::protobuf::uint32 BovoMessage::y() const {
  // @@protoc_insertion_point(field_get:bovo_message.BovoMessage.y)
  return y_;
}
inline void BovoMessage::set_y(::google::protobuf::uint32 value) {
  _has_bits_[0] |= 0x00000080u;
  y_ = value;
  // @@protoc_insertion_point(field_set:bovo_message.BovoMessage.y)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace bovo_message

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::bovo_message::BovoMessage_CmdType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bovo_message::BovoMessage_CmdType>() {
  return ::bovo_message::BovoMessage_CmdType_descriptor();
}
template <> struct is_proto_enum< ::bovo_message::BovoMessage_StatusType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::bovo_message::BovoMessage_StatusType>() {
  return ::bovo_message::BovoMessage_StatusType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_msg_2eproto
